import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


def create_alert_email(
    anomaly_summary,
    recommendations,
    sender_name="AI Business Intelligence Analyst"
):
    """
    Creates the executive anomaly alert email.
    """

    timestamp = datetime.now().strftime("%d %B %Y, %I:%M %p")

    # Convert anomaly summary into readable text
    if isinstance(anomaly_summary, dict):
        summary_text = ""

        for key, value in anomaly_summary.items():
            title = str(key).replace("_", " ").title()

            if isinstance(value, list):
                summary_text += f"<h3>{title}</h3><ul>"

                for item in value:
                    summary_text += f"<li>{item}</li>"

                summary_text += "</ul>"

            else:
                summary_text += (
                    f"<p><strong>{title}:</strong> "
                    f"{value}</p>"
                )

    else:
        summary_text = f"<p>{anomaly_summary}</p>"

    # Recommendations
    recommendation_text = ""

    if isinstance(recommendations, list):

        recommendation_text = "<ul>"

        for recommendation in recommendations:
            recommendation_text += (
                f"<li>{recommendation}</li>"
            )

        recommendation_text += "</ul>"

    elif isinstance(recommendations, dict):

        recommendation_text = "<ul>"

        for key, value in recommendations.items():
            recommendation_text += (
                f"<li><strong>"
                f"{str(key).replace('_', ' ').title()}"
                f":</strong> {value}</li>"
            )

        recommendation_text += "</ul>"

    else:
        recommendation_text = (
            f"<p>{recommendations}</p>"
        )

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif;">

        <h2>🚨 AI Business Intelligence Alert</h2>

        <p>
            <strong>Generated:</strong> {timestamp}
        </p>

        <p>
            The AI Business Intelligence Analyst has detected
            potentially significant business anomalies that may
            require management attention.
        </p>

        <hr>

        <h2>📊 Anomaly Summary</h2>

        {summary_text}

        <hr>

        <h2>💡 Recommended Actions</h2>

        {recommendation_text}

        <hr>

        <p>
            This alert was automatically generated by
            <strong>{sender_name}</strong>.
        </p>

        <p>
            Please review the dashboard and executive report
            for detailed analysis.
        </p>

    </body>
    </html>
    """

    return html


def send_email_alert(
    sender_email,
    sender_password,
    receiver_email,
    subject,
    html_content
):
    """
    Sends the executive alert through Gmail SMTP.
    """

    try:

        message = MIMEMultipart("alternative")

        message["From"] = sender_email
        message["To"] = receiver_email
        message["Subject"] = subject

        html_part = MIMEText(
            html_content,
            "html"
        )

        message.attach(html_part)

        with smtplib.SMTP(
            "smtp.gmail.com",
            587
        ) as server:

            server.starttls()

            server.login(
                sender_email,
                sender_password
            )

            server.sendmail(
                sender_email,
                receiver_email,
                message.as_string()
            )

        return True, "Email alert sent successfully."

    except Exception as e:

        return False, f"Email sending failed: {str(e)}"